- hosts: localhost
  vars:
    username: "harley"
    source_key: "./.ssh/id_ed25519"
    dest_key: "/home/{{ username }}/.ssh/id_ed25519"
    tooling: "/home/{{ username }}/tooling"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  - name: Create directory for install tooling
    file:
      path: "{{ tooling }}"
      state: directory
    tags:
      - core
  tasks:
    - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/core-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/tools.yml
    - include: tasks/node.yml
    - include: tasks/lsp.yml
    - include: tasks/dotfiles.yml
