- name: Install System Packages 1 (build-essential, cmake, pkg-config, pthread, cland)
  become: true
  apt:
    name: ["build-essential", "cmake", "pkg-config", "libpthread-stubs0-dev", "clang"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2 (lua, unzip, libtool, libtool-bin, gettext)
  become: true
  apt:
    name: [ "lua5.1", "unzip", "libtool", "libtool-bin", "gettext"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 3
  become: true
  apt:
    name: [ "curl", "htop", "ripgrep", "fd-find" ]
  tags:
    - install
    - core
- name: Install System Packages 4
  become: true
  apt:
    name: [ "python3-pip", "python-is-python3", "python3-venv"]
  tags:
    - install
    - core
