- name: Installing stow
  become: true
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/harleylara/dotfiles.git'
    dest: "/home/{{ username }}/dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
