- name: Install latex related packages
  become: true
  apt:
    name: ["texlive-latex-base", "latexmk"]
    update_cache: yes
  tags:
    - latex
    - install
    - core
- name: Install tree-sitter-cli (requirement for latex)
  become: true
  npm:
    name: tree-sitter-cli
    global: yes
  tags:
    - lsp
    - latex
