- name: Dependencies for build sumneko lua lsp
  become: true
  apt:
    name: ["ninja-build", "build-essential"]
  tags:
    - lsp
    - lua

- name: Get sumneko lua lsp
  git:
    repo: "https://github.com/sumneko/lua-language-server"
    recursive: yes
    dest: "{{ tooling }}/sumneko"
  tags:
    - lsp
    - lua

- name: Build Lua lsp from source
  shell:
    cmd: ./make.sh
    chdir: "{{ tooling }}/sumneko/"
  tags:
    - lsp
    - lua

- name: Install tsserver lsp for javascript
  become: true
  npm:
    name: typescript-language-server
    global: yes
  tags:
    - lsp
    - javascript

- name: Install typescript (requirement for lsp)
  become: true
  npm:
    name: typescript
    global: yes
  tags:
    - lsp
    - javascript

- name: Install pyright
  become: true
  npm:
    name: pyright
    global: yes
  tags:
    - lsp
    - python

- name: Install clangd for c, c++ and others c
  become: true
  apt:
    name: clangd
  tags:
    - lsp
    - c
    - c++
- name: Install go
  become: true
  apt:
    name: golang-go
  tags:
    - lsp
    - go
    - gopls
