- name: Clone n (Node version manager)
  git:
    repo: "https://github.com/tj/n.git"
    dest: "{{ lookup('env', 'HOME') }}/tooling/n"
  tags:
    - node
    - lsp

- name: Install n
  become: true
  shell:
    cmd: make install
    chdir: "{{ lookup('env', 'HOME') }}/tooling/n" 
  tags:
    - node
    - lsp

- name: Install npm and node
  become: true
  shell:
    cmd: n 16
  tags:
    - node
    - lsp
