- name: Remove neovim
  shell: "rm -rf {{ tooling }}/neovim"
  tags:
    - install
    - neovim
# Build Neovim from source: https://github.com/neovim/neovim/blob/master/BUILD.md
- name: Install prerequisites for build neovim in Debian-based systems
  become: true
  apt:
    name:
      - ninja-build
      - gettext
      - cmake
      - curl
      - build-essential
      - git
  tags:
    - neovim
- name: Clone Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ tooling }}/neovim"
  tags:
    - neovim
- name: Checkout stable Neovim
  shell:
    chdir: "{{ tooling }}/neovim"
    cmd: git checkout v0.12.1
  tags:
    - neovim
- name: Build neovim
  become: true
  shell: "cd {{ tooling }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ tooling }}/neovim && make install"
  tags:
    - neovim
