- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
- name: Install Packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - install
    - neovim
# Build Neovim from source: https://github.com/neovim/neovim/wiki/Building-Neovim
- name: Install prerequisites for build neovim
  become: true
  apt:
    name: ["ninja-build", "gettext", "libtool", "libtool-bin", "autoconf", "automake", "cmake", "g++", "pkg-config", "unzip", "curl", "doxygen"]
  tags:
    - neovim
- name: Clone Neovim
  git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ tooling }}/neovim"
  tags:
    - neovim
- name: Checkout stable Neovim
  shell:
    cmd: git checkout stable
    chdir: "{{ tooling }}/neovim"
  tags:
    - neovim
- name: Build neovim
  shell: "cd {{ tooling }}/neovim && make CMAKE_BUILD_TYPE=RelWithDebInfo"
  tags:
    - neovim
- name: Install neovim
  become: true
  shell: "cd {{ tooling }}/neovim && make install"
  tags:
    - install
