- name: Install packages (tmux, fzf, neofetch)
  become: true
  apt:
    name: [ "tmux", "fzf", "neofetch", "net-tools" ]
  tags:
    - install
    - tools
- name: Install Yazi (Ensure dependencies)
  become: true
  apt:
    name:
      - curl
      - build-essential
      - pkg-config
      - libssl-dev
    state: present
  tags:
    - install
    - tools
    - yazi
- name: Install Rust via rustup
  shell: |
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: /root/.cargo/bin/rustup
  tags:
    - install
    - tools
    - yazi
- name: Update Rust toolchain
  shell: "{{ ansible_env.HOME }}/.cargo/bin/rustup update"
  tags:
    - install
    - tools
    - yazi
- name: Clone the Yazi repository
  git:
    repo: https://github.com/sxyazi/yazi.git
    dest: /tmp/yazi
    version: main
  tags:
    - install
    - tools
    - yazi
- name: Build Yazi using cargo
  shell: "{{ ansible_env.HOME }}/.cargo/bin/cargo build --release --locked"
  args:
    chdir: /tmp/yazi
  tags:
    - install
    - tools
    - yazi
- name: Move Yazi binaries to /usr/local/bin
  become: true
  copy:
    src: "{{ item }}"
    dest: /usr/local/bin/
    mode: '0755'
    remote_src: yes
  loop:
    - /tmp/yazi/target/release/yazi
    - /tmp/yazi/target/release/ya
  tags:
    - install
    - tools
    - yazi
