- name: Install packages (tmux, fzf, neofetch)
  become: true
  apt:
    name: [ "tmux", "fzf", "neofetch", "net-tools" ]
  tags:
    - install
    - tools
- name: Install dependencies for dwm
  become: true
  apt:
    name: [libx11-dev, libxft-dev, libxinerama-dev, libfreetype6-dev, libfontconfig1-dev]
  tags:
    - desktop
