- name: Install packages (tmux, fzf, neofetch)
  become: true
  apt:
    name: [ "tmux", "fzf", "neofetch", "net-tools" ]
  tags:
    - install
    - tools
- name: Install dependencies for dwm
  become: true
  apt:
    name: [libx11-dev, libxft-dev, libxinerama-dev, libfreetype6-dev, libfontconfig1-dev]
  tags:
    - desktop
- name: Get dwm
  git:
    repo: "https://git.suckless.org/dwm"
    recursive: yes
    dest: "{{ tooling }}/dwm"
  tags:
    - desktop
- name: Build dwm
  become: true
  shell:
    cmd: make clean install
    chdir: "{{ tooling }}/dwm"
  tags:
    - desktop
- name: Get dmenu
  git:
    repo: "https://git.suckless.org/dmenu"
    recursive: true
    dest: "{{ tooling }}/dmenu"
  tags:
    - desktop
- name: Build dmenu
  become: true
  shell:
    cmd: make clean install
    chdir: "{{ tooling }}/dmenu"
  tags:
    - desktop
- name: Get st
  git:
    repo: "https://git.suckless.org/st"
    recursive: true
    dest: "{{ tooling }}/st"
  tags:
    - desktop
- name: Build st
  become: true
  shell:
    cmd: make clean install
    chdir: "{{ tooling }}/st"
  tags:
    - desktop
